// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import core "github.com/fibercrypto/fibercryptowallet/src/core"
import mock "github.com/stretchr/testify/mock"

// BlockchainVisor is an autogenerated mock type for the BlockchainVisor type
type BlockchainVisor struct {
	mock.Mock
}

// ScanOutputs provides a mock function with given fields: unspentOnly
func (_m *BlockchainVisor) ScanOutputs(unspentOnly bool) (core.TransactionOutputIterator, error) {
	ret := _m.Called(unspentOnly)

	var r0 core.TransactionOutputIterator
	if rf, ok := ret.Get(0).(func(bool) core.TransactionOutputIterator); ok {
		r0 = rf(unspentOnly)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(core.TransactionOutputIterator)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(bool) error); ok {
		r1 = rf(unspentOnly)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SendFromAddress provides a mock function with given fields: from, to, change, options
func (_m *BlockchainVisor) SendFromAddress(from []core.Address, to []core.TransactionOutput, change core.Address, options core.KeyValueStore) (core.Transaction, error) {
	ret := _m.Called(from, to, change, options)

	var r0 core.Transaction
	if rf, ok := ret.Get(0).(func([]core.Address, []core.TransactionOutput, core.Address, core.KeyValueStore) core.Transaction); ok {
		r0 = rf(from, to, change, options)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(core.Transaction)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func([]core.Address, []core.TransactionOutput, core.Address, core.KeyValueStore) error); ok {
		r1 = rf(from, to, change, options)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Spend provides a mock function with given fields: unspent, new, change, options
func (_m *BlockchainVisor) Spend(unspent []core.TransactionOutput, new []core.TransactionOutput, change core.Address, options core.KeyValueStore) (core.Transaction, error) {
	ret := _m.Called(unspent, new, change, options)

	var r0 core.Transaction
	if rf, ok := ret.Get(0).(func([]core.TransactionOutput, []core.TransactionOutput, core.Address, core.KeyValueStore) core.Transaction); ok {
		r0 = rf(unspent, new, change, options)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(core.Transaction)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func([]core.TransactionOutput, []core.TransactionOutput, core.Address, core.KeyValueStore) error); ok {
		r1 = rf(unspent, new, change, options)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Transfer provides a mock function with given fields: to, options
func (_m *BlockchainVisor) Transfer(to core.TransactionOutput, options core.KeyValueStore) (core.Transaction, error) {
	ret := _m.Called(to, options)

	var r0 core.Transaction
	if rf, ok := ret.Get(0).(func(core.TransactionOutput, core.KeyValueStore) core.Transaction); ok {
		r0 = rf(to, options)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(core.Transaction)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(core.TransactionOutput, core.KeyValueStore) error); ok {
		r1 = rf(to, options)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
