// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import core "github.com/fibercrypto/fibercryptowallet/src/core"
import mock "github.com/stretchr/testify/mock"

// BlockchainExplorer is an autogenerated mock type for the BlockchainExplorer type
type BlockchainExplorer struct {
	mock.Mock
}

// GetBlockByHash provides a mock function with given fields: hash
func (_m *BlockchainExplorer) GetBlockByHash(hash string) (core.Block, error) {
	ret := _m.Called(hash)

	var r0 core.Block
	if rf, ok := ret.Get(0).(func(string) core.Block); ok {
		r0 = rf(hash)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(core.Block)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(hash)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetBlocksInRange provides a mock function with given fields: start, end
func (_m *BlockchainExplorer) GetBlocksInRange(start uint64, end uint64) ([]core.Block, error) {
	ret := _m.Called(start, end)

	var r0 []core.Block
	if rf, ok := ret.Get(0).(func(uint64, uint64) []core.Block); ok {
		r0 = rf(start, end)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]core.Block)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(uint64, uint64) error); ok {
		r1 = rf(start, end)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
